In [43]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Set the paths to the image data folders
positive_data_dir = 'Datasets/Glaucoma Dataset - 2'
# negative_data_dir = '/content/drive/MyDrive/Fundus_Scanes_Sorted/Train/Glaucoma_Negative'

# Define the parameters for the model
image_width, image_height = 150, 150
input_shape = (image_width, image_height, 3)
batch_size = 32
epochs = 12
num_classes = 4

# Create the data generator and load the images
data_generator = ImageDataGenerator(rescale=1./255)
train_data = data_generator.flow_from_directory(
    directory=positive_data_dir,
    target_size=(image_width, image_height),
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=True
)

# Create the model architecture
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=input_shape),
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(
    train_data,
    steps_per_epoch=train_data.samples // batch_size,
    epochs=epochs
)

# Save the trained model
model.save('glaucoma_model.h5')


Found 4218 images belonging to 4 classes.
Epoch 1/12
131/131 ━━━━━━━━━━━━━━━━━━━━ 83s 619ms/step - accuracy: 0.5566 - loss: 1.0358
Epoch 2/12
131/131 ━━━━━━━━━━━━━━━━━━━━ 1s 353us/step - accuracy: 0.9375 - loss: 0.3537  
Epoch 3/12


c:\Users\dhani\AppData\Local\Programs\Python\Python311\Lib\contextlib.py:158: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(typ, value, traceback)


131/131 ━━━━━━━━━━━━━━━━━━━━ 81s 615ms/step - accuracy: 0.7544 - loss: 0.5727
Epoch 4/12
131/131 ━━━━━━━━━━━━━━━━━━━━ 1s 81us/step - accuracy: 0.7812 - loss: 0.3971   
Epoch 5/12
131/131 ━━━━━━━━━━━━━━━━━━━━ 69s 529ms/step - accuracy: 0.8023 - loss: 0.4785
Epoch 6/12
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 101us/step - accuracy: 0.7500 - loss: 0.4460 
Epoch 7/12
131/131 ━━━━━━━━━━━━━━━━━━━━ 66s 506ms/step - accuracy: 0.8079 - loss: 0.4505
Epoch 8/12
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 93us/step - accuracy: 0.9062 - loss: 0.3314  
Epoch 9/12
131/131 ━━━━━━━━━━━━━━━━━━━━ 64s 485ms/step - accuracy: 0.8359 - loss: 0.3913
Epoch 10/12
131/131 ━━━━━━━━━━━━━━━━━━━━ 1s 91us/step - accuracy: 0.9375 - loss: 0.3607   
Epoch 11/12
131/131 ━━━━━━━━━━━━━━━━━━━━ 69s 525ms/step - accuracy: 0.8243 - loss: 0.4151
Epoch 12/12
131/131 ━━━━━━━━━━━━━━━━━━━━ 1s 108us/step - accuracy: 0.8438 - loss: 0.3824  


In [5]:
# pip install pillow
import tensorflow as tf

In [6]:
model = tf.keras.models.load_model('glaucoma_model.h5')

In [7]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import array_to_img, img_to_array, load_img
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.preprocessing import image
import numpy as np
from keras import backend as K

In [22]:
# Cataract
img_prd = load_img('Datasets\Glaucoma Dataset - 2\cataract\_3_4674992.jpg',target_size=(150,150))
img_prd = img_to_array(img_prd)
img_pred = np.expand_dims(img_prd, axis=0)

result = model.predict(img_pred)
print(result)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
[[1. 0. 0. 0.]]


In [29]:
# Cataract
img_prd = load_img('Datasets\Glaucoma Dataset - 2\cataract\_9_1244013.jpg',target_size=(150,150))
img_prd = img_to_array(img_prd)
img_pred = np.expand_dims(img_prd, axis=0)

result = model.predict(img_pred)
print(result)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
[[1. 0. 0. 0.]]


In [30]:
# Diabetic
img_prd = load_img('Datasets/Glaucoma Dataset - 2/diabetic_retinopathy/10003_right.jpeg',target_size=(150,150))
img_prd = img_to_array(img_prd)
img_pred = np.expand_dims(img_prd, axis=0)

result = model.predict(img_pred)
print(result)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
[[0. 1. 0. 0.]]


In [31]:
# Diabetic
img_prd = load_img('Datasets/Glaucoma Dataset - 2/diabetic_retinopathy/1012_left.jpeg',target_size=(150,150))
img_prd = img_to_array(img_prd)
img_pred = np.expand_dims(img_prd, axis=0)

result = model.predict(img_pred)
print(result)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
[[0. 1. 0. 0.]]


In [35]:
# Glaucoma
img_prd = load_img('Datasets\Glaucoma Dataset - 2\glaucoma\_7_5314686.jpg',target_size=(150,150))
img_prd = img_to_array(img_prd)
img_pred = np.expand_dims(img_prd, axis=0)

result = model.predict(img_pred)
print(result)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
[[0. 0. 1. 0.]]


In [36]:
# Normal
img_prd = load_img('Datasets/Glaucoma Dataset - 2/normal/2335_left.jpg',target_size=(150,150))
img_prd = img_to_array(img_prd)
img_pred = np.expand_dims(img_prd, axis=0)

result = model.predict(img_pred)
print(result)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
[[0. 0. 0. 1.]]
